# Generated by Django 2.2.3 on 2019-09-05 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_drop_all_tables'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attributes',
            new_name='Attribute',
        ),
    ]
